import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useQuery } from '@tanstack/react-query';
import { Link } from 'react-router-dom';
import { fetchLeases } from '../lib/api';
import PageHeader from '../components/PageHeader';
import SectionCard from '../components/SectionCard';
export default function Agreements() {
    const { data: leases = [], isLoading } = useQuery({ queryKey: ['leases'], queryFn: fetchLeases });
    return (_jsxs("div", { className: "space-y-6", children: [_jsx(PageHeader, { title: "Agreements", description: "Every lease, its status, and quick links to payments and repairs." }), isLoading ? (_jsx("p", { className: "text-muted", children: "Loading\u2026" })) : (_jsx(SectionCard, { children: _jsxs("table", { className: "min-w-full text-sm", children: [_jsx("thead", { children: _jsxs("tr", { className: "text-left text-muted", children: [_jsx("th", { className: "p-3 font-semibold text-foreground/80", children: "Lease" }), _jsx("th", { className: "p-3 font-semibold text-foreground/80", children: "Property" }), _jsx("th", { className: "p-3 font-semibold text-foreground/80", children: "Tenant" }), _jsx("th", { className: "p-3 font-semibold text-foreground/80", children: "Rent (ETH)" }), _jsx("th", { className: "p-3 font-semibold text-foreground/80", children: "Start" }), _jsx("th", { className: "p-3 font-semibold text-foreground/80", children: "End" }), _jsx("th", { className: "p-3 font-semibold text-foreground/80", children: "Chain" }), _jsx("th", { className: "p-3 font-semibold text-foreground/80", children: "Tx hash" }), _jsx("th", { className: "p-3", colSpan: 3 })] }) }), _jsxs("tbody", { children: [leases.map((lease) => (_jsxs("tr", { className: "border-t border-outline/40", children: [_jsx("td", { className: "p-3 font-semibold text-foreground", children: lease.id.slice(0, 6) }), _jsx("td", { className: "p-3 text-foreground", children: lease.listing?.title || 'Listing' }), _jsx("td", { className: "p-3 text-muted", children: lease.tenant?.email || '—' }), _jsx("td", { className: "p-3 text-foreground", children: Number(lease.annualRentEth || 0).toFixed(2) }), _jsx("td", { className: "p-3 text-muted", children: lease.startISO ? lease.startISO.slice(0, 10) : '—' }), _jsx("td", { className: "p-3 text-muted", children: lease.endISO ? lease.endISO.slice(0, 10) : '—' }), _jsx("td", { className: "p-3 text-muted", children: lease.chainId || '—' }), _jsx("td", { className: "p-3 font-mono text-xs text-muted", children: lease.txHash ? `${lease.txHash.slice(0, 10)}…` : '—' }), _jsx("td", { className: "p-3 text-right", children: _jsx(Link, { to: `/agreements/${lease.id}`, className: "text-brand font-medium hover:text-brand-hover", children: "View" }) }), _jsx("td", { className: "p-3 text-right", children: _jsx(Link, { to: `/payments/${lease.id}`, className: "text-sm text-muted hover:text-foreground", children: "Payments" }) }), _jsx("td", { className: "p-3 text-right", children: _jsx(Link, { to: `/repairs/${lease.id}`, className: "text-sm text-muted hover:text-foreground", children: "Repairs" }) })] }, lease.id))), !leases.length && (_jsx("tr", { children: _jsx("td", { colSpan: 9, className: "p-4 text-center text-muted", children: "No leases yet." }) }))] })] }) }))] }));
}
